[BuildOptions]
build_variant = release
build_args = []
force_build = []
force_all = false
macos_codesign = false

[USDOptions]
# build_type: SHARED_LIBS = 0, MONOLITHIC_LIB = 1
build_type = 0
build_tests = false
build_examples = true
build_tutorials = true
build_tools = true
build_docs = false
build_python_docs = false
build_python = true
safety_first = true
build_usd_validation = true
debug_python = false

[ImagingOptions]
# build_imaging: NO_IMAGING = 0, IMAGING = 1, USD_IMAGING = 2
build_imaging = 2
enable_ptex = false
enable_openvdb = false
build_usdview = true
build_zlib = true
enable_vulkan = false

[PluginOptions]
build_embree = false
build_prman = false
build_oiio = false
build_ocio = false
build_alembic = false
enable_hdf5 = false
build_draco = false
build_materialx = true
build_onetbb = false

[TestOptions]
build_mayapy_tests = false
build_animx_tests = false 
